### PR TITLE
[Silex2] Cleanup

### PR DESCRIPTION
**Pull request by jdreesen**
Since Silex 2 requires PHP >= 5.5 we can now use `::class`.
I also fixed some small typos and removed some unused imports.

### CODE REVIEW

**Comment by mnapoli** [comment]
https://www.youtube.com/watch?v=a8c5wmeOL9o

By the way if want to enable https://styleci.io for this repo feel free to do it

**Comment by jdreesen** [comment]
I'll have a look into styleci.io.

**Comment by mnapoli** [comment]
Yep it's just a suggestion though, I personally find it quite fun but sometimes it can be a pain (configuring all rules to match the current style, or adapting to their new rules popping up every 3 months, etc.)

**Comment by jdreesen** [comment]
I'll play around with it a bit and then maybe enable it eventually.
But I'm not sure how I could enable it for this repo because it shows only repos that are on my own account. I enabled it for my fork of this repo for now.

**Comment by mnapoli** [comment]
OK just let me know if you want me to enable it

**Pull request merged**
