### PR TITLE
Initial support for upcoming Silex version 2

### LINKED ISSUE #6: Silex v2 compatibility
Hi,

Could you make branch compatible with silex dev-master branch ? Because I can't use Silex-Bridge with her dependencies.

Regards,

### PR DESCRIPTION
**Pull request by jdreesen**
This should add initial support for the upcoming Silex 2. 

As I'm not actively using Silex at the moment it would be nice if someone actually using it (@Atriedes?) does a quick review if I forgot something. 
Anyhow, the tests are running fine.

closes #6

### CODE REVIEW

**Comment by mnapoli** [comment]
Waiting for a review from @Atriedes or anyone using Silex 2 before merging.

**Comment by ricardokenji** [comment]
I'm not really using it, but converted a lumen application to silex2 + php-di to test performance and did almost the same things, i only forgot to unset()  the exception_handler in the base_test.

**Comment by mnapoli** [comment]
YOLO! :p

I won't tag a stable version of this branch until Silex 2 is released anyway.

**Comment by mnapoli** [comment]
And thanks @jdreesen!

**Pull request merged**
